on:
  pull_request:
    branches:
      - main
      - master
      
  push:
    branches:
      - main
      - master
      
name: "Build & Release"
jobs:
  build:
    name: Build & Release
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '11.x'
      - uses: subosito/flutter-action@v1
        with:
          channel: stable
      - run: flutter clean
      - run: flutter pub get
      
      - run: flutter build appbundle
      - run: flutter build apk
      - run: flutter build apk --release 

    
      - name: Push to Releases
        uses: ncipollo/release-action@v1
        with:
          artifacts: build/app/outputs/bundle/release/app-release.aab, build/app/outputs/apk/release/app-release.apk
          tag: v1.0.${{ github.run_number }}